seed_everything: 333
trainer:
  gpus: [0] 
  callbacks:
    - class_path: lightning_modules.callbacks.span_selection_save_prediction_callback.SavePredictionCallback
      init_args:
        test_set: &prediction_set test # {dev, test}, also change line 34
        input_dir: &input_dir_path dataset/reasoning_module_input
        output_dir: output/span_selection_output
        
  accelerator: gpu
  strategy: ddp_find_unused_parameters_false

model:
  class_path: lightning_modules.models.span_selection_model.SpanSelectionModel
  init_args:
    model_name: &transformer t5-base
    optimizer:
      init_args: 
        lr: 0.0
    lr_scheduler:
      name: linear
      init_args:
        num_warmup_steps: 100
        num_training_steps: 10000
    test_set: test_inference.json # no usage here
    input_dir: *input_dir_path

data:
  class_path: lightning_modules.datasets.span_selection_reader.SpanSelectionInferenceDataModule
  init_args:
    model_name: *transformer
    batch_size: 128
    test_file_path: ./dataset/reasoning_module_input/test_inference.json
    test_max_instances: -1
    entity_name: predicted_question_type
    

# For Inference
# clear; export PYTHONPATH=`pwd`; python trainer.py predict --ckpt_path checkpoints/span_selection_model.ckpt --config inference_configs/span_selection_inference.yaml